services:
  riscv-dev:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: riscv-dev
    volumes:
      - ../workspace:/workspace:rw
      - ../workspace/opcodes:/root/riscv-dev/riscv-opcodes/opcodes:rw
      - ../workspace/binutils-patches:/patches/binutils:rw
      - ../workspace/gcc-patches:/patches/gcc:rw
      - ../workspace/tests:/tests:rw
      - ../workspace/projects:/projects:rw
    working_dir: /workspace
    tty: true
    stdin_open: true
    environment:
      - UMASK=000
      - RISCV=/opt/riscv
      - PATH=/opt/riscv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command: /bin/bash -c "chmod -R 777 /workspace && umask 000 && /bin/bash"
