services:
  toolchain:
    image: ghcr.io/hytalo-bassi/riscv-prod:latest
    working_dir: /opt
    volumes:
      - shared-workspace:/workspace:rw
    command: >
      bash -c "
      sleep infinity"

  gem5-base:
    image: ghcr.io/hytalo-bassi/gem5-base:latest
    working_dir: /opt/gem5
    volumes:
      - gem5-build-cache:/opt/gem5/build
      - ../Approx_Instructions:/approx:ro
      - ../patches/gem5/decoder.isa:/opt/gem5/src/arch/riscv/isa/decoder.isa:ro
      - ../patches/gem5/ext/softfloat/SConscript:/opt/gem5/ext/softfloat/SConscript:ro
      - ../patches/gem5/ext/softfloat/internals.h:/opt/gem5/ext/softfloat/internals.h:ro
      - ../patches/gem5/ext/softfloat/softfloat.h:/opt/gem5/ext/softfloat/softfloat.h:ro
      - ../patches/gem5/src/cpu/o3/iew.cc:/opt/gem5/src/cpu/o3/iew.cc:ro
      - ../patches/gem5/src/cpu/o3/iew.hh:/opt/gem5/src/cpu/o3/iew.hh:ro
      - shared-workspace:/workspace:rw
    command: >
      bash -c "
      cp /approx/*.c /opt/gem5/ext/softfloat/ &&
      sleep infinity"

  gem5-full:
    image: ghcr.io/hytalo-bassi/gem5-full:latest
    working_dir: /opt/gem5
    volumes:
      - shared-workspace:/workspace:rw
    command: >
      bash -c "
      sleep infinity
      "

volumes:
  gem5-build-cache:
  shared-workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/workspace
  shared-workspace-projects:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/workspace/projects