# choose the service with
# docker compose -f docker/compose.yaml up <service_name> -d
services:
  base:
    build:
      context: ..
      dockerfile: docker/build/Dockerfile.base
    image: lscad/base-riscv-image:latest
    environment:
      - PATH=/opt/riscv-linux/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  riscv-gem5:
    build: 
      context: ..
      dockerfile: docker/build/Dockerfile.gem5
    image: lscad/build-riscv-gem5:latest
    depends_on:
      - base
    container_name: riscv-gem5
    volumes:
      - shared-workspace:/workspace:rw
      - shared-workspace-projects:/projects:rw
    working_dir: /workspace
    tty: true
    stdin_open: true
    environment:
      - UMASK=000
      - RISCV=/opt/riscv
      - PATH=/opt/riscv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    command: /bin/bash -c "chmod -R 777 /workspace && umask 000 && /bin/bash"

volumes:
  shared-workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/workspace
  shared-workspace-projects:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/workspace/projects
