services:
  base:
    build:
      context: ..
      dockerfile: docker/build/Dockerfile.base
    image: lscad/base-riscv-image:latest

  gem5-base:
    image: lscad/gem5-base
    working_dir: /opt/gem5
    volumes:
      - gem5-build-cache:/opt/gem5/build
      - ../Approx_Instructions:/approx:ro
      - ../patches/gem5/decoder.isa:/opt/gem5/src/arch/riscv/isa/decoder.isa:ro
      - ../patches/gem5/ext/softfloat/SConscript:/opt/gem5/ext/softfloat/SConscript:ro
      - ../patches/gem5/ext/softfloat/internals.h:/opt/gem5/ext/softfloat/internals.h:ro
      - ../patches/gem5/ext/softfloat/softfloat.h:/opt/gem5/ext/softfloat/softfloat.h:ro
      - shared-workspace:/workspace:rw
    command: >
      bash -c "
        cp /approx/*.c /opt/gem5/ext/softfloat/ &&
        sleep infinity"
  gem5-build:
    image: lscad/gem5-base
    working_dir: /opt/gem5
    volumes:
      - gem5-build-cache:/opt/gem5/build
      - ../Approx_Instructions:/approx:ro
      - ../patches/gem5/decoder.isa:/opt/gem5/src/arch/riscv/isa/decoder.isa:ro
      - ../patches/gem5/ext/softfloat/SConscript:/opt/gem5/ext/softfloat/SConscript:ro
      - ../patches/gem5/ext/softfloat/internals.h:/opt/gem5/ext/softfloat/internals.h:ro
      - ../patches/gem5/ext/softfloat/softfloat.h:/opt/gem5/ext/softfloat/softfloat.h:ro
      - shared-workspace:/workspace:rw
    command: >
      bash -c "
        cp /approx/*.c /opt/gem5/ext/softfloat/ &&
        cd /opt/gem5 &&
        scons build/RISCV/gem5.fast --linker=${LINKER:-gold} -j${BUILD_JOBS:-1}
      "

volumes:
  gem5-build-cache:
  shared-workspace:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/workspace
  shared-workspace-projects:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/workspace/projects
